### ISSUE TITLE
Did not decode any data when next or prev in Info are null

### ISSUE THREAD

**Issue by MaximAfanasenko** [benjaminbruch/rick-morty-swift-api#1]

**Comment by benjaminbruch** [comment]
Hey Maxim, could please provide an example call, where you get that error?

**Comment by benjaminbruch** [comment]
[FIXED] with commit https://github.com/benjaminbruch/rick-morty-swift-api/commit/4eaac2da4f57c2a60e3ced8f72897955382999fe
